Project/Controllers/Manager_item_in_saleController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class Manager_item_in_saleController : Controller
    {
        private P2Entities2 db = new P2Entities2();

        // GET: item_in_sale
        public ActionResult Index()
        {
            var item_in_sale = db.item_in_sale.Include(i => i.city).Include(i => i.sale).Include(i => i.item);
            return View(item_in_sale.ToList());
        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var item = db.size.Where(t => t.id_item == id).ToList();
            if (item.Count() == 0)
            {
                //הצגת המידות לכל פריט מטבלת מידות
                var item1 = db.item_in_sale.Find(id);
                List<size> size = new List<size>();
                size ez = new size();
                ez.item_in_sale = item1;
                size.Add(ez);
                if (item1 == null)
                {
                    return HttpNotFound();

                }
                return View(size);
            }

            return View(item);
        }
        // GET: item_in_sale/Create
        public ActionResult Create()
        {
            ViewBag.itsale_itemsale = new SelectList(db.city, "id_city", "name_city");
            ViewBag.idneighborhood_sale = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
            //ViewBag.iditem_itemsale = new SelectList(db.sale, "id_sale", "name_sale");
            ViewBag.iditem_itemsale = new SelectList(db.sale, "id_sale", "id_sale");
            ViewBag.iditems = new SelectList(db.item, "id_item", "name_item");
            return View();
        }

        // POST: item_in_sale/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_itemsale,itsale_itemsale,iditem_itemsale,size_itemsale,amountinstock_itemsale,iditems")] item_in_sale item_in_sale)
        {
            try
            {
                if (ModelState.IsValid)
                {

                    item_in_sale.size_itemsale = 0;
                    item_in_sale.amountinstock_itemsale = 0;
             
                    db.item_in_sale.Add(item_in_sale);
                    db.SaveChanges();
                    //הוספת כמות לכל מידה שהכניסו
                    List<int> s = new List<int>();
                    int index1 = db.item.Find(item_in_sale.iditems).sizeinstock_item.IndexOf('-');
                    if (index1 != -1)
                    {
                        string start = item_in_sale.item.sizeinstock_item.Substring(0, item_in_sale.item.sizeinstock_item.LastIndexOf("-"));
                        string end = item_in_sale.item.sizeinstock_item.Remove(0, item_in_sale.item.sizeinstock_item.LastIndexOf("-") + 1);
                        if (item_in_sale.item.id_i_category != 4)
                        {// מידות לפרטי לבוש זוגי בלבד
                            if (Convert.ToInt16(start) % 2 != 0 || Convert.ToInt16(end) % 2 != 0)
                            {
                                ViewBag.error1 = "נא הכנס מידות זוגיות בלבד";
                                return View(item_in_sale);
                            }
                            for (int i = Convert.ToInt16(start); i <= Convert.ToInt16(end); i += 2)
                            {
                                s.Add(i);
                            }
                        }
                        else
                        {//מידות לנעליים
                            for (int i = Convert.ToInt16(start); i <= Convert.ToInt16(end); i++)
                            {
                                s.Add(i);
                            }
                        }

                    }
                    else
                        s.Add(Convert.ToInt16(item_in_sale.item.sizeinstock_item));
                    List<size> listSize = new List<size>();
                    for (int i = 0; i < s.Count(); i++)
                    {
                        size size = new size();
                        size.n_size = s[i];
                        size.id_item = item_in_sale.id_itemsale;
                        listSize.Add(size);
                    }
                    CustomerClientVM ccVM = new CustomerClientVM();

                    ccVM.listSize = listSize;
                    return View("~/Views/Manager_sizes/Create.cshtml", ccVM);
                }

                ViewBag.itsale_itemsale = new SelectList(db.city, "id_city", "name_city");
                ViewBag.idneighborhood_sale = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
               // ViewBag.iditem_itemsale = new SelectList(db.sale, "id_sale", "name_sale");
                ViewBag.iditem_itemsale = new SelectList(db.sale, "id_sale", "id_sale");
                ViewBag.iditems = new SelectList(db.item, "id_item", "name_item");
                return View(item_in_sale);
        } 
                    catch
                    {
                ViewBag.itsale_itemsale = new SelectList(db.city, "id_city", "name_city");
                ViewBag.idneighborhood_sale = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
                //ViewBag.iditem_itemsale = new SelectList(db.sale, "id_sale", "name_sale");
                ViewBag.iditem_itemsale = new SelectList(db.sale, "id_sale", "id_sale");
                ViewBag.iditems = new SelectList(db.item, "id_item", "name_item");
                ViewBag.error = ".ארעה שגיאה בשמירת הפרטים";
                        return View();
                     }
}

// GET: item_in_sale/Edit/5
public ActionResult Edit(int? id)
{
    try
    {
        if (id == null)
        {
            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }
        item_in_sale item_in_sale = db.item_in_sale.Find(id);
        if (item_in_sale == null)
        {
            return HttpNotFound();
        }
        ViewBag.itsale_itemsale = new SelectList(db.city, "id_city", "name_city", item_in_sale.itsale_itemsale);
        ViewBag.iditem_itemsale = new SelectList(db.sale, "id_sale", "name_sale", item_in_sale.iditem_itemsale);
        ViewBag.iditems = new SelectList(db.item, "id_item", "name_item", item_in_sale.iditems);
        return View(item_in_sale);
    }
    catch
    {
        ViewBag.error = ".ארעה שגיאה בעדכון הפרטים";
        return View();
    }
}

        ////        // POST: item_in_sale/Edit/5
        ////        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        ////        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_itemsale,itsale_itemsale,iditem_itemsale,size_itemsale,amountinstock_itemsale,iditems")] item_in_sale item_in_sale)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int sw = 0;
                    var ez = db.item.Find(item_in_sale.item.id_item);
                    if (ez.sizeinstock_item != item_in_sale.item.sizeinstock_item)
                    {
                        sw = 1;//השתנו המידות
                    }
                    ez.sizeinstock_item = item_in_sale.size_itemsale.ToString();
                    var entity = db.item_in_sale.Where(b => b.id_itemsale == item_in_sale.id_itemsale).AsQueryable().FirstOrDefault();
                    db.Entry(entity).CurrentValues.SetValues(item_in_sale);
                     var entity1 = db.item.Where(b => b.id_item == ez.id_item).AsQueryable().FirstOrDefault();
                    db.Entry(entity1).CurrentValues.SetValues(ez);
                    db.SaveChanges();
                    if (sw == 1)
                    {
                        //אם הזינו מידות חדשות - מחיקת המידות הישנות מטבלת מידות והזנת כמויות למידות החדשות שהוזנו
                        db.size.RemoveRange(db.size.Where(c => c.item_in_sale.id_itemsale == item_in_sale.id_itemsale));
                        db.SaveChanges();
                        List<int> s = new List<int>();
                        int index1 = item_in_sale.item.sizeinstock_item.IndexOf('-');
                        if (index1 != -1)
                        {
                            string start = item_in_sale.item.sizeinstock_item.Substring(0, item_in_sale.item.sizeinstock_item.LastIndexOf("-"));
                            string end = item_in_sale.item.sizeinstock_item.Remove(0, item_in_sale.item.sizeinstock_item.LastIndexOf("-") + 1);
                            if (item_in_sale.item.id_i_category != 4)
                            {// מידות לפרטי לבוש זוגי בלבד
                                if (Convert.ToInt16(start) % 2 != 0 || Convert.ToInt16(end) % 2 != 0)
                                {
                                    ViewBag.error1 = "נא הכנס מידות זוגיות בלבד";
                                    return View(item_in_sale);
                                }
                                for (int i = Convert.ToInt16(start); i <= Convert.ToInt16(end); i += 2)
                                {
                                    s.Add(i);
                                }
                            }
                            else
                            {//מידות לנעליים
                                for (int i = Convert.ToInt16(start); i <= Convert.ToInt16(end); i++)
                                {

Project/Views/Manager_item_in_sale/Create.cshtml
@model Project.Models.item_in_sale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<h3 align="right">חדש</h3>
<div class="leftpane">
    <br /><br />
    <br />
    <img src="~/pictures/6.png" style="width:450px;height:300px" />
</div>
@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal" align="right">

    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.DisplayName("מוצר")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("iditems", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.iditems, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("מכירה")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("iditem_itemsale", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.iditem_itemsale, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.DisplayName("עיר")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("itsale_itemsale", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.itsale_itemsale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("שכונה")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("idneighborhood_sale", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.itsale_itemsale, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2" align="right">
            <input type="submit" value="המשך" class="btn btn-my" />&nbsp;&nbsp;&nbsp;
            <input type="button" value="ביטול" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
        </div>
    </div>
</div>
}

Project/Views/Manager_item_in_sale/Delete.cshtml
@model Project.Models.item_in_sale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}



<h3 align="right">מחיקה</h3>
<div class="leftpane">
    <br /><br />
    <br />
    <img src="~/pictures/18-806x567.png" style="width:450px;height:300px" />
</div>
<div align="right">
    <br />
    <dl class="dl-horizontal" style="margin-left:80%">
        <dt>
            @Html.DisplayFor(model => model.sale.name_sale)
        </dt>

        <dd>
            @Html.DisplayName("מכירה")
        </dd>

        <dt>
            @Html.DisplayFor(model => model.city.name_city)
        </dt>
        <dd>
            @Html.DisplayName("עיר")
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="margin-left:50%">
            <div class="col-md-offset-2">
                <input type="submit" value="מחיקה" class="btn btn-my" />&nbsp;&nbsp;&nbsp;
                <input type="button" value="ביטול" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
            </div>
        </div>

    }
</div>

Project/Views/Manager_item_in_sale/Details.cshtml
@model IEnumerable<Project.Models.size>

@{
    ViewBag.Title = "details";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}
<h3 align="right">פרטים נוספים</h3>
<div class="leftpane">
    <br /><br />
    <br />
    <img src="~/pictures/8-1-806x567.png" style="width:450px;height:300px" />
</div>
<div align="right">
    <br />
    <dl class="dl-horizontal" style="margin-left:75%">

        @foreach (var item in Model)
        {


            <dt>
                @Html.DisplayFor(model => item.item_in_sale.item.name_item)
            </dt>

            <dd>
                @Html.DisplayName("מוצר")
            </dd>

            <dt>
                @Html.DisplayFor(model => item.item_in_sale.item.price_item)
            </dt>


            <dd>
                @Html.DisplayName("מחיר")
            </dd>
            <dt>
                @Html.DisplayFor(model => item.item_in_sale.item.color_item)
            </dt>

            <dd>
                @Html.DisplayName("צבע")
            </dd>

            <dt>
                @Html.DisplayFor(model => item.item_in_sale.item.limitedamount_item)
            </dt>

            <dd>
                @Html.DisplayName("כמות מוגבלת")
            </dd>


            <dt>
                @Html.DisplayFor(model => item.item_in_sale.item.type_item.name_type)
            </dt>
            <dd>
                @Html.DisplayName("סוג")
            </dd>


            <dt>
                @Html.DisplayFor(model => item.item_in_sale.item.category_item.name_category)
            </dt>
            <dd>
                @Html.DisplayName("קטגוריה")
            </dd>
            break;
        }

        @foreach (var item in Model)
        {
            <dt>
                @Html.DisplayFor(model => item.n_size)
            </dt>

            <dd>
                @Html.DisplayName("מידה")
            </dd>
            <dt>
                @Html.DisplayFor(model => item.amount)
            </dt>

            <dd>
                @Html.DisplayName("כמות")
            </dd>
        }


        <dd>
            @Html.DisplayName("תמונה")
        </dd>
    </dl>
    @foreach (var item in Model)
    {
        <img src="@Html.DisplayFor(model => item.item_in_sale.item.picture_item)" style="height:150px;display:inline-block;" />
        break;
    }
    <br /><br />
    <div>
        <input type="button" value="חזרה" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
    </div>
</div>

Project/Views/Manager_item_in_sale/Edit.cshtml
@model Project.Models.item_in_sale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<h3 align="right">עדכון</h3>
<div class="leftpane">
    <br /><br />
    <br />

    <img src="~/pictures/9.png" style="width:450px;height:300px" />
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" align="right">

        <br />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id_itemsale)
        <div class="form-group">
            @Html.DisplayName("מוצר")
            <div class="col-md-10">
                @Html.DropDownList("iditems", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iditems, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.DisplayName("מכירה")
            <div class="col-md-10">
                @Html.DropDownList("iditem_itemsale", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.iditem_itemsale, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.DisplayName("עיר")
            <div class="col-md-10">
                @Html.DropDownList("itsale_itemsale", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.itsale_itemsale, "", new { @class = "text-danger" })
            </div>
        </div>

    </div>
    <div class="form-group" style="margin-left:50%">
        <div class="col-md-offset-2 ">
            <input type="submit" value="שמירה" class="btn btn-my" />&nbsp;&nbsp;&nbsp;
            <input type="button" value="ביטול" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
        </div>
    </div>
}

Project/Views/Manager_item_in_sale/Index.cshtml
@model IEnumerable<Project.Models.item_in_sale>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<h2 style="margin-left:8%">מוצרים במכירה</h2>

<h3 style="margin-left:96%">
    @Html.ActionLink("חדש", "Create")
</h3>
@using (Ajax.BeginForm("Search", "Manager_item_in_sale", new AjaxOptions()
{
    HttpMethod = "post",
    UpdateTargetId = "divSearchResults",
    InsertionMode = InsertionMode.Replace
}))
{
    <div align="right">
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
        </button>
        <input type="text" class="btn btn-default searchTxt" name="searchTxt" placeholder="חיפוש לפי מוצר /מכירה/ עיר" />

    </div>
}

    <div id="divSearchResults">
        <br />
        <table class="table" style="text-align:left;">
            <tr class="tr11">
                <th></th>
                <th>
                    @Html.DisplayName("כתובת")
                </th>
                <th>
                    @Html.DisplayName("עיר")
                </th>
                <th>
                    @Html.DisplayName("מכירה")
                </th>

                <th>
                    @Html.DisplayName("מוצר")
                </th>
                <th>
                    @Html.DisplayName("קוד מוצר")
                </th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.ActionLink("עדכון", "Edit", new { id = item.id_itemsale }) |
                        @Html.ActionLink("פרטים", "Details", new { id = item.id_itemsale }) |
                        @Html.ActionLink("מחיקה", "Delete", new { id = item.id_itemsale })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.sale.addressSale)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.city.name_city)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.sale.name_sale)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.item.name_item)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.item.id_item)
                    </td>


                </tr>
            }

        </table>
    </div>

Project/Views/Manager_item_in_sale/Search.cshtml
@model IEnumerable<Project.Models.item_in_sale>
@{
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<script src="~/scripts/jquery-1.7.1.min.js"></script>
<script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>




 
<div id="divSearchResults">
    @using (Ajax.BeginForm("Search", "Manager_item_in_sale", new AjaxOptions()
    {
        HttpMethod = "post",
        UpdateTargetId = "divSearchResults",
        InsertionMode = InsertionMode.Replace
    }))
    {
        <div align="right">
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>
            </button>
            <input type="text" class="btn btn-default searchTxt" name="searchTxt" placeholder="חיפוש לפי מוצר /מכירה/ עיר" />

        </div>
    }
    <h4 class="text-danger" align="right">@ViewBag.error9</h4>
    @if (Model != null)
    {
        <br />
        <table class="table" style="text-align:left;">
            <tr class="tr11">
                <th></th>
                <th>
                    @Html.DisplayName("מידה")
                </th>
                <th>
                    @Html.DisplayName("כמות")
                </th>
                <th>
                    @Html.DisplayName("עיר")
                </th>
                <th>
                    @Html.DisplayName("מכירה")
                </th>

                <th>
                    @Html.DisplayName("מוצר")
                </th>
                <th>
                    @Html.DisplayName("קוד מוצר")
                </th>

            </tr>

            @foreach (var item in Model)
            {
                <tr>

                    <td>
                        @Html.ActionLink("עדכון", "Edit", new { id = item.id_itemsale }) |
                        @Html.ActionLink("מחיקה", "Delete", new { id = item.id_itemsale })
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.size_itemsale)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.amountinstock_itemsale)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.city.name_city)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.sale.name_sale)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.item.name_item)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.item.id_item)
                    </td>


                </tr>
            }

        </table>}
</div>