Project/Controllers/Manager_clientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;
using System.ComponentModel.DataAnnotations;

using System.Net.Mail;
using iTextSharp.text.pdf;
using iTextSharp.text;
using System.IO;
using System.Drawing;

namespace Project.Controllers
{
    public class IdShoppesc
    {
        public static int IdShoppes = 0;
    };
    public class Manager_clientsController : Controller
    {
        private P2Entities2 db = new P2Entities2();
        int check = 0;
        // המציג למשתמש את פרטיו בסיום קניה view
        [HttpGet]
        public ActionResult CreateShopper()
        {
            var IdCustomer = Session["password"];
            if (IdCustomer != null)
            {
                var old = db.client.FirstOrDefault(x => x.id_client.ToString() == IdCustomer.ToString());

                if (old != null)
                {
                    ViewBag.NameCustomer = old.nameclient;
                    ViewBag.PasswordCustomer = old.id_client;
                    ViewBag.PhoneCustomer = old.phone_client;
                    ViewBag.AddressCustomer = old.address_client;

                }
                else
                {//במקרה שהמשתמש לא קיים- הצגת הודעת שגיאה
                    ViewBag.error = "you don't exist";

                }
            }
            return View();
        }

        // GET: Manager_clients
        public ActionResult Index()
        {
            var client = db.client.Include(c => c.city).Include(c => c.neighborhood).Include(c => c.users);
            return View(client.ToList());
        }

        // GET: Manager_clients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }

        // GET: Manager_clients/Create
        public ActionResult Create()
        {
            ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city");
            ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
            ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user");
            return View();
        }
        
        // POST: Manager_clients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_client,iduser_client,tz_client,address_client,idcity_client,idneighborhood_client,phone_client,fatherjob_client,avgsalary_client,email_client,nameclient,lastorder_client,numchildren_client,tz_client,passwordc,salary1,salary2,salary3")] client client)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    client.avgsalary_client = (Convert.ToInt16(client.salary1) + Convert.ToInt16(client.salary2) + Convert.ToInt16(client.salary3)) / 3;
                    db.client.Add(client);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city", client.idcity_client);
                ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood", client.idneighborhood_client);
                ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user", client.iduser_client);
                return View(client);
            } 
            catch
            {
                ViewBag.error = ".ארעה שגיאה בעת שמירת הפרטים";
                return View();
            }
        }

        // GET: Manager_clients/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city", client.idcity_client);
            ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood", client.idneighborhood_client);
            ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user", client.iduser_client);
            return View(client);
        }

        // POST: Manager_clients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_client,iduser_client,address_client,idcity_client,idneighborhood_client,phone_client,fatherjob_client,avgsalary_client,email_client,nameclient,lastorder_client,numchildren_client,tz_client,passwordc,salary1,salary2,salary3")] client client)
        {
            ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city", client.idcity_client);
            ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood", client.idneighborhood_client);
            ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user", client.iduser_client);
            if (ModelState.IsValid)
            {
                client.avgsalary_client = (Convert.ToInt16(client.salary1) + Convert.ToInt16(client.salary2) + Convert.ToInt16(client.salary3)) / 3;
                db.Entry(client).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city", client.idcity_client);
            ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood", client.idneighborhood_client);
            ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user", client.iduser_client);
            return View(client);
        }

        // GET: Manager_clients/Delete/5
        public ActionResult Delete(int? id)
        {
           try{
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
            }
            catch
            {
                ViewBag.error = ".ארעה שגיאה בעת שליחת הנתונים";
                return View();
            }
        }

        // POST: Manager_clients/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try {
                client client = db.client.Find(id);
                db.children.RemoveRange(db.children.Where(c => c.idclient_child == id));
                db.tblfiles.RemoveRange(db.tblfiles.Where(c => c.id_c == id));
                db.client.Remove(client);
                db.SaveChanges();
            return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.error = ".ארעה שגיאה בעת מחיקת הנתונים";
                return View();
            }
        }
        //סיום הזמנה ושליחת ההזמנה למייל
        public ActionResult endShop()
        {
            var IdCustomer = Session["tzC"].ToString();
            //הצגת המחיר הסופי ללקוח
            ViewBag.s = DBShopinCart.lShopingCard.Sum(x => x.price_item * x.Amount);
            //הצגת התאריך הנוכחי ללקוח
            ViewBag.d = DateTime.Today;
            var s = db.client.FirstOrDefault(x => x.tz_client.ToString() == IdCustomer.ToString());
            if (IdCustomer != null && s.address_client != null)
            { //הוספת קניה חדשה לרשימת הקניות בעת קניה
                orders ts = new orders();
                ts.date_order = DateTime.Today;
                ts.idclient_order = s.id_client;
                db.orders.Add(ts);
                db.SaveChanges();
                int kod = ts.id_order;
                myStatistics mys = new myStatistics();
                List<MyShoppingCart> shop = new List<MyShoppingCart>();
                shop = DBShopinCart.lShopingCard.Where(y => y.itemInWait != 1).ToList();
                foreach (var item in shop)
                {
                    var ise = db.item_in_sale.Find(item.id_item);
                    order_details sd = new order_details();
                    sd.amount_details= item.Amount;
                    sd.iditem_details = ise.item.id_item;
                    sd.idorder_details = kod;
                    sd.size_details =Convert.ToInt32(item.sizeinstock_item);
                    sd.price = (float)item.price_item;
                    db.order_details.Add(sd);
                    db.SaveChanges();
                    mys.amount = item.Amount;
                    mys.ids_neighborhood = s.neighborhood.id_neighborhood;
                    mys.id_city = s.city.id_city;
                    mys.id_item = ise.item.id_item;
                    mys.id_type = ise.item.type_item.id_type;
                    mys.last_order = DateTime.Today;
                    mys.size =Convert.ToInt32( item.sizeinstock_item);
                    mys.id_category = ise.item.category_item.id_category;

Project/Views/Manager_clients/Create.cshtml
@model Project.Models.client

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<h3 align="right">חדש</h3>
<div class="leftpane">
    <br /><br />
    <br />
    <img src="~/pictures/6.png" style="width:450px;height:300px" />
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group" align="right">
        @Html.DisplayName("סוג משתמש")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("iduser_client", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.iduser_client, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" align="right">
        @Html.DisplayName("סיסמה")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.passwordc, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.passwordc, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" align="right">
        @Html.DisplayName("תעודת זהות")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.tz_client, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.tz_client, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" align="right">
        @Html.DisplayName("שם")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.nameclient, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.nameclient, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group" align="right">
        @Html.DisplayName("עיר")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("idcity_client", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.city.name_city, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" align="right">
        @Html.DisplayName("שכונה")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("idneighborhood_client", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idneighborhood_client, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" align="right">
        @Html.DisplayName("כתובת")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.address_client, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.address_client, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" align="right">
        @Html.DisplayName("טלפון")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.phone_client, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.phone_client, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" align="right">
        @Html.DisplayName("כתובת מייל")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.email_client, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.email_client, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" align="right">
        @Html.DisplayName("עיסוק האב")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.fatherjob_client, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fatherjob_client, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group" align="right">
        <div class="col-md-13">
            <label> @Html.DisplayName(" הכנס/י משכורת לשלשת החודשים האחרונים")</label>
        </div>
        <br />
        <div>
            @Html.EditorFor(model => model.salary1, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.salary1, "", new { @class = "text-danger" })
        </div>
        <br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.salary2, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.salary2, "", new { @class = "text-danger" })
        </div>
        <br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.salary3, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.salary3, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" align="right">
        @Html.DisplayName("מספר ילדים")
        <br /><br />
        <div class="col-md-13" align="right">
            @Html.EditorFor(model => model.numchildren_client, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.numchildren_client, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group" align="right">
        <br /><br />
        @Html.DisplayName("ההזמנה האחרונה")
        <div class="col-md-13">
            @Html.EditorFor(model => model.lastorder_client, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lastorder_client, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        <div class="col-md-offset-2" align="right">
            <input type="submit" value="שמירה" class="btn btn-my" />&nbsp;&nbsp;&nbsp;
            <input type="button" value="ביטול" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
        </div>
    </div>
</div>
}

Project/Views/Manager_clients/CreateShopper.cshtml
@model Project.Models.client

@{
    ViewBag.Title = "Create";
}

<h2>M&E JEWELRIES</h2>
<h3 class="text-danger">@ViewBag.error</h3>
<form method="get" action="@Url.Action("Create","Manager_orders")">
    @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.DisplayName("ת.ז")
            <div class="col-md-10 btn btn-default glyphicon glyphicon-star" style="font-size:20px;width:50px;"></div>
            <div>
                <input type="password" placeholder="@ViewBag.PasswordCustomer" name="IdCustomer" value="@Request["IdCustomer"]" class="form-control" />
                @Html.ValidationMessageFor(model => model.id_client, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.DisplayName("שם")<div class="col-md-10 btn btn-default glyphicon glyphicon-user" style="font-size:20px;width:50px;"></div>
            <div>
                <input type="text" placeholder="@ViewBag.NameCustomer" class="form-control" />
                @Html.ValidationMessageFor(model => model.nameclient, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.DisplayName("כתובת")<div class="col-md-10 btn btn-default glyphicon glyphicon-user" style="font-size:20px;width:50px;"></div>
            <div>
                <input type="text" placeholder="@ViewBag.NameCustomer" class="form-control" />
                @Html.ValidationMessageFor(model => model.address_client, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.DisplayName("שכונה")<div class="col-md-10 btn btn-default glyphicon glyphicon-share" style="font-size:20px;width:50px;"></div>
            <div>
                <input type="text" placeholder="@ViewBag.AddressCustomer" class="form-control" />
                @Html.ValidationMessageFor(model => model.neighborhood, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.DisplayName("עיר")<div class="col-md-10 btn btn-default glyphicon glyphicon-user" style="font-size:20px;width:50px;"></div>
            <div>
                <input type="text" placeholder="@ViewBag.NameCustomer" class="form-control" />
                @Html.ValidationMessageFor(model => model.city, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.DisplayName("טלפון")<div class="col-md-10 btn btn-default glyphicon glyphicon-phone" style="font-size:20px;width:50px;"></div>
            <div>
                <input type="text" placeholder="@ViewBag.PhoneCustomer" class="form-control" />
                @Html.ValidationMessageFor(model => model.phone_client, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.DisplayName("כתובת מייל")<div class="col-md-10 btn btn-default glyphicon glyphicon-user" style="font-size:20px;width:50px;"></div>
            <div>
                <input type="text" placeholder="@ViewBag.NameCustomer" class="form-control" formaction="@Url.Action("endShop","Manager_clients")" />
                @Html.ValidationMessageFor(model => model.email_client, "", new { @class = "text-danger" })
            </div>
        </div>


    </div>
    <input type="submit" value="שמירה" class="btn btn-default" formaction="@Url.Action("endShop","Manager_clients")" />
    }
    </form>


 

Project/Views/Manager_clients/Delete.cshtml
@model Project.Models.client

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}



<h3 align="right">מחיקה</h3>
<div class="leftpane">
    <br /><br />
    <br />
    <img src="~/pictures/18-806x567.png" style="width:450px;height:300px" />
</div>
<div align="right">
    <br />
    <dl class="dl-horizontal" style="margin-left:80%">
        <dt>
            @Html.DisplayFor(model => model.id_client)
        </dt>
        <dd>
            @Html.DisplayName("קוד")
        </dd>


        <dt>
            @Html.DisplayFor(model => model.users.name_user)
        </dt>

        <dd>
            @Html.DisplayName("סוג משתמש")
        </dd>

        <dt>
            @Html.DisplayFor(model => model.passwordc)
        </dt>
        <dd>
            @Html.DisplayName("סיסמה")
        </dd>

        <dt>
            @Html.DisplayFor(model => model.tz_client)
        </dt>
        <dd>
            @Html.DisplayName("תעודת זהות")
        </dd>



        <dt>
            @Html.DisplayFor(model => model.nameclient)
        </dt>
        <dd>
            @Html.DisplayName("שם")
        </dd>
        <dt>
            @Html.DisplayFor(model => model.city.name_city)
        </dt>

        <dd>
            @Html.DisplayName("עיר")
        </dd>



        <dt>
            @Html.DisplayFor(model => model.neighborhood.name_neighborhood)
        </dt>
        <dd>
            @Html.DisplayName("שכונה")
        </dd>

        <dt>
            @Html.DisplayFor(model => model.address_client)
        </dt>
        <dd>
            @Html.DisplayName("כתובת")
        </dd>








        <dt>
            @Html.DisplayFor(model => model.phone_client)
        </dt>
        <dd>
            @Html.DisplayName("טלפון")
        </dd>


        <dt>
            @Html.DisplayFor(model => model.email_client)
        </dt>
        <dd>
            @Html.DisplayName("כתובת מייל")
        </dd>




        <dt>
            @Html.DisplayFor(model => model.fatherjob_client)
        </dt>

        <dd>
            @Html.DisplayName("עיסוק האב")
        </dd>
        <dt>
            @Html.DisplayFor(model => model.avgsalary_client)
        </dt>

        <dd>
            @Html.DisplayName("ממוצע משכורות")
        </dd>


        <dt>
            @Html.DisplayFor(model => model.numchildren_client)
        </dt>


        <dd>
            @Html.DisplayName("מספר ילדים")
        </dd>

        <dt>
            @Html.DisplayFor(model => model.lastorder_client)
        </dt>


        <dd>
            @Html.DisplayName("ההזמנה האחרונה")
        </dd>


    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="margin-left:50%">
            <div class="col-md-offset-2">
                <input type="submit" value="מחיקה" class="btn btn-my" />&nbsp;&nbsp;&nbsp;
                <input type="button" value="ביטול" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
            </div>
        </div>

    }
</div>

Project/Views/Manager_clients/Index.cshtml
@model IEnumerable<Project.Models.client>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<h2 style="margin-left:8%">רשומים</h2>

<h3 style="margin-left:96%">
    @Html.ActionLink("חדש", "Create")
</h3>

@using (Ajax.BeginForm("Search", "Manager_clients", new AjaxOptions()
{
    HttpMethod = "post",
    UpdateTargetId = "divSearchResults",
    InsertionMode = InsertionMode.Replace
}))
{
<div  align="right">
    <button type="submit" class="btn btn-default">
        <span class="glyphicon glyphicon-search"></span>
    </button>
    <input type="text" class="btn btn-default searchTxt" name="searchTxt" placeholder="חיפוש לפי שם / ת.ז" />
  
</div>
}

<div id="divSearchResults">
    <br />
    <table class="table" style="text-align:left;">
        <tr class="tr11">

            <th></th>

            <th>
                @Html.DisplayName("כתובת מייל")
            </th>
            <th>
                @Html.DisplayName("טלפון")
            </th>
            <th>
                @Html.DisplayName("שכונה")
            </th>
            <th>
                @Html.DisplayName("עיר")
            </th>
            <th>
                @Html.DisplayName("כתובת")
            </th>
            <th>
                @Html.DisplayName("שם")
            </th>
            <th>
                @Html.DisplayName("תעודת זהות")
            </th>
            <th>
                @Html.DisplayName("סוג משתמש")
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink("עדכון", "Edit", new { id = item.id_client }) |
                    @Html.ActionLink("פרטים", "Details", new { id = item.id_client }) |
                    @Html.ActionLink("מחיקה", "Delete", new { id = item.id_client })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.email_client)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.phone_client)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.neighborhood.name_neighborhood)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.city.name_city)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.address_client)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.nameclient)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.tz_client)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.users.name_user)
                </td>




            </tr>
        }

    </table>
 
</div>

Project/Views/Manager_clients/Search.cshtml
@model IEnumerable<Project.Models.client>
@{
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<script src="~/scripts/jquery-1.7.1.min.js"></script>
<script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>




 
<div id="divSearchResults">
    <h2 style="margin-left:8%">רשומים</h2>

    <h3 style="margin-left:96%">
        @Html.ActionLink("חדש", "Create")
    </h3>
    <div style="margin-right:10%">
        @using (Ajax.BeginForm("Search", "Manager_clients", new AjaxOptions()
        {
            HttpMethod = "post",
            UpdateTargetId = "divSearchResults",
            InsertionMode = InsertionMode.Replace
        }))
        {
            <div align="right">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
                <input type="text" class="btn btn-default" name="searchTxt" placeholder="חיפוש לפי שם / ת.ז" />

            </div>
        }
        </div>
        <h4 class="text-danger" align="right">@ViewBag.error9</h4>
        @if (Model != null)
        {
            <table class="table" style="text-align:left;">
                <tr class="tr11">

                    <th></th>

                    <th>
                        @Html.DisplayName("ממוצע משכורות")
                    </th>

                    <th>
                        @Html.DisplayName("עיסוק האב")
                    </th>
                    <th>
                        @Html.DisplayName("כתובת מייל")
                    </th>
                    <th>
                        @Html.DisplayName("טלפון")
                    </th>
                    <th>
                        @Html.DisplayName("שכונה")
                    </th>
                    <th>
                        @Html.DisplayName("עיר")
                    </th>
                    <th>
                        @Html.DisplayName("כתובת")
                    </th>
                    <th>
                        @Html.DisplayName("שם")
                    </th>
                    <th>
                        @Html.DisplayName("תז")
                    </th>
                    <th>
                        @Html.DisplayName("סוג משתמש")
                    </th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.ActionLink("עדכון", "Edit", new { id = item.id_client }) |
                            @Html.ActionLink("פרטים", "Details", new { id = item.id_client }) |
                            @Html.ActionLink("מחיקה", "Delete", new { id = item.id_client })
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.avgsalary_client)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.fatherjob_client)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.email_client)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.phone_client)
                        </td>

                        <td>
                            @Html.DisplayFor(modelItem => item.idneighborhood_client)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.idcity_client)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.address_client)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.nameclient)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.tz_client)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.iduser_client)
                        </td>




                    </tr>
                }

            </table>}
    </div>

Project/Views/Manager_clients/endShop.cshtml
@model Project.Models.modelOfItemAndCategory
@{
    Layout = "~/Views/Shared/_ManagerShopingLayout.cshtml";
    ViewBag.Title = "andShop";
}
<link href="~/Content/bootstrap.css" rel="stylesheet" />
<script src="~/scripts/jquery-1.7.1.min.js"></script>
<script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>
<script src="~/Scripts/modernizr-2.6.2.js"></script>
<script src="~/scripts/bootstrap.min.js"></script>


<link href="~/Content/stylesheet_rivka.css" rel="stylesheet" />
<link href="~/Content/w3.css" rel="stylesheet" />
<div id="divSearchResults">
    <h2>סיום הזמנה</h2>
    <h4 class="text-danger">@ViewBag.error1</h4>
    <br />
    <h4 class="text-danger">@ViewBag.error2</h4>

    <h1 class="text-success">@ViewBag.success</h1>
    <h4>
        @Html.ActionLink("הורד הזמנה", "DownloadPDF", "Manager_clients", new { id = -1 }, FormMethod.Post)
    </h4><br />
    </div>