Project/Controllers/CustomerClientsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Project.Models;
using System.Net.Mail;
using System.Text;

namespace Project.Controllers
{
    public class CustomerClientsController : Controller
    {
        private P2Entities2 db = new P2Entities2();

        // GET: CustomerClients
        public ActionResult Index()
        {
            var client = db.client.Include(c => c.city).Include(c => c.neighborhood).Include(c => c.users);
            return View(client.ToList());
        }
        public ActionResult IndexFile()
        {
            var tz = Session["tzC"];
            client c = db.client.FirstOrDefault(a => a.tz_client == tz);
            var tblfiles = db.tblfiles.Where(t => t.id_c==c.id_client);
            return View(tblfiles.ToList());
        }
        // GET: CustomerClients/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            return View(client);
        }
        //פונקציה לשליחת קוד לנרשם במייל 
        public void sendEmailAsync(string ToEmail, string UserName, string nPassword)/*string UniqeId(int id, string code)*/
        {
            try
            {
                MailMessage mail = new MailMessage(); //("organizationmc1@gmail.com", ToEmail"miriamyahud@neto.net.il", "מלבושי כבוד");
                mail.From = new MailAddress("organizationmc1@gmail.com", "מלבושי כבוד");
                mail.To.Add(ToEmail);
                StringBuilder sbEmailbody = new StringBuilder();
                sbEmailbody.Append("לכבוד " + UserName + ",<br/><br/>");
                sbEmailbody.Append("פרטיך נשמרו בהצלחה, הסיסמה שלך הינה " + nPassword);
                sbEmailbody.Append("<br/><br/>");
                sbEmailbody.Append("<b>מלבושי כבוד<b>");

                mail.IsBodyHtml = true;

                mail.Body = sbEmailbody.ToString();
                mail.Subject = " סיסמה למלבושי כבוד";
                SmtpClient smtpClient = new SmtpClient
                {
                    Host = "smtp.gmail.com",
                    Port = 587,
                    EnableSsl = true,
                    DeliveryMethod = SmtpDeliveryMethod.Network,
                    Credentials = new NetworkCredential("organizationmc1@gmail.com", "123456789mc")
                };
                smtpClient.Send(mail);
            }
            catch
            { }
        }
        // GET: CustomerClients/Create
        public ActionResult Create()
        {
            ViewBag.name = Session["name"];
            ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city");
            ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
            ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user");
            return View();
        }

        // POST: CustomerClients/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        
        public ActionResult Create([Bind(Include = "id_client,tz_client,iduser_client,address_client,idcity_client,idneighborhood_client,phone_client,avgsalary_client,email_client,nameclient,numchildren_client,lastorder_client,salary1,salary2,salary3,salary4")]
        client client, string fjob, string mjob)
        {
            try
            {
                if (fjob == "1")
                    fjob = "לא עובד";
                else
                    fjob = "עובד";
                if (mjob == "1")
                    mjob = "לא עובד";
                else
                    mjob = "עובד";
                //רישום של משתמש חדש
                client.fatherjob_client = fjob;
                client.motherjob_client = mjob;
                int minFamsize = db.setting.Min(mi => mi.minfamsize_setting);
                int maxSallary = db.setting.Max(ma => ma.maxsalary_setting);
                var fatherjob = db.setting.Max(f => f.fatherjob_setting);
                client.avgsalary_client = (Convert.ToInt16(client.salary1) + Convert.ToInt16(client.salary2) + Convert.ToInt16(client.salary3) + Convert.ToInt16(client.salary4)) / 4;
                var c = client.avgsalary_client / client.numchildren_client;
                if ((client.avgsalary_client < maxSallary && client.numchildren_client > minFamsize) && (client.fatherjob_client == "לא עובד"||client.motherjob_client=="לא עובד"  && c < 2500)||
                    (client.fatherjob_client == "עובד" && client.motherjob_client == "עובד"  && c < 1900))
                {
                    client.tz_client =Session["tz"].ToString();
                    client.passwordc = Session["password"].ToString();
                    client.nameclient = Session["name"].ToString();
                    client.iduser_client = 4;
                    db.client.Add(client);
                    db.SaveChanges();
                    Session.Add("idC",client.id_client);
                    sendEmailAsync(client.email_client, client.nameclient, client.passwordc);
                    Session.Add("nameC", Session["name"].ToString());
                    ViewBag.name = Session["name"].ToString();
                    //שליחת רשימת ילדים למילוי לפי מספר ילדים שהמשתמש הכניס
                    List<children> listChildren = new List<children>();
                    for (int i = 0; i < client.numchildren_client; i++)
                    {
                        children children = new children();
                        children.idclient_child = client.id_client;
                        listChildren.Add(children);
                    }

                    CustomerClientVM ccVM = new CustomerClientVM();

                    ccVM.listChlidren = listChildren;
                    ViewBag.name = Session["nameC"].ToString();

                    return View("CreateDetails", ccVM);
                }
                else
                {
                    ViewBag.name = Session["name"];
                    ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city");
                    ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
                    ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user");
                    ViewBag.error = "מצטערים אך אינך עונה לקריטריונים של הארגון";
                    return View();
                }
            }
            catch
            {
            ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city");
            ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
            ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user");
                return View(client);
            }

            
        }

// GET: CustomerClients/Edit/5
public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            client client = db.client.Find(id);
            if (client == null)
            {
                return HttpNotFound();
            }
            ViewBag.idcity_client = new SelectList(db.city, "id_city", "name_city");
            ViewBag.idneighborhood_client = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
            ViewBag.iduser_client = new SelectList(db.users, "id_user", "name_user");
            return View(client);
        }

        // POST: CustomerClients/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_client,iduser_client,address_client,idcity_client,idneighborhood_client,phone_client,avgsalary_client,email_client,nameclient,lastorder_client,numchildren_client,tz_client,passwordc,salary1,salary2,salary3,salary4")] client client, string fjob, string mjob)
        {
            int check = 0;
            if (fjob == "1")
                fjob = "לא עובד";
            else
                fjob = "עובד";
            if (mjob == "1")
                mjob = "לא עובד";
            else
                mjob = "עובד";
            client.fatherjob_client = fjob;
            client.motherjob_client = mjob;
            if (ModelState.IsValid)
            {  
                //עדכון פרטים של משתמש קיים
                int maxSallary = db.setting.Max(ma => ma.maxsalary_setting);
                int minFamsize = db.setting.Min(mi => mi.minfamsize_setting);
                var fatherjob = db.setting.Max(f => f.fatherjob_setting);
                client.avgsalary_client = (Convert.ToInt16(client.salary1) + Convert.ToInt16(client.salary2) + Convert.ToInt16(client.salary3) + Convert.ToInt16(client.salary4)) / 4;
                var c = client.avgsalary_client / client.numchildren_client;
                if ((client.avgsalary_client < maxSallary && client.numchildren_client > minFamsize) && (client.fatherjob_client == "לא עובד" || client.motherjob_client == "לא עובד" && c < 2500) ||
                   (client.fatherjob_client == "עובד" && client.motherjob_client == "עובד" && c < 1900))
                {

Project/Views/CustomerClients/CreateDetails.cshtml
@using Project.Models
@model CustomerClientVM
@{
    ViewBag.Title = "CreateDetails";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}
@*<script src="~/scripts/jquery-1.7.1.min.js"></script>
<script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>*@
<body>
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog" >

            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title right">  !@ViewBag.name  שלום</h4>
                </div>
                <br />
                <br />
                @using (Html.BeginForm("Create", "Customer_children", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                <div class="form-horizontal" align="center">
                    @for (int i = 0; i < Model.listChlidren.Count; i++)
                    {
                        <h1>@ViewBag.id</h1>
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                        @Html.HiddenFor(model => model.listChlidren[i].id_child)
                        @Html.HiddenFor(model => model.listChlidren[i].idclient_child)
                        <div class="form-group">
                            <div  style="margin:auto">
                                <label> @Html.DisplayName(" הכנס/י תאריך לידה ")</label>
                                <div class="col-md-8" style="margin:auto">
                                    @Html.EditorFor(model => model.listChlidren[i].birthdate_child, new { htmlAttributes = new { @class = "form-control MakeWide s" } })
                                    @Html.ValidationMessageFor(model => model.listChlidren[i].birthdate_child, "", new { @class = "text-danger" })
                                </div>
                            </div>
                            </div>
                        <div class="form-group">
                            <div style="margin:auto">
                                <label> @Html.DisplayName(" הכנס/י מין ")</label>
                                <div class="col-md-8" style="margin:auto">
                                    @Html.DropDownListFor(model => model.listChlidren[i].m_f_child,
                                            new SelectList(Enum.GetValues(typeof(Gender))),"זכר", new { @class = "form-control MakeWide s" })
                                </div>
                            </div>
                        </div>
                    }
                    <div class="modal-footer" style="text-align:center">
                        <input type="submit" value="המשך" class="w3-button blue-button" />
                    </div>
                </div>

                }


            </div>
                    </div>
    </div>
</body>
<script type="text/javascript">

    $(window).on('load', function () {
        setTimeout(
            function () {
                $('#myModal').modal('show');
            }, 2000);

    });
    $('#myModal').modal({
        backdrop: 'static',
        keyboard: false
    })

</script>
<style>
    .MakeWide {
        width: 250px;
    }

    .modal-content {
        min-height: 100px;
        height: auto;
        margin: 80px auto 0px auto;
    }
    .s {
        width: 220px;
    }

</style>

Project/Views/CustomerClients/DeleteFile.cshtml
@model Project.Models.tblfiles

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title right">  !@ViewBag.name  שלום</h4>
            </div>
            <div class="modal-body">
                <br />
               
                    <h5 style="font-weight:bold" align="right">@Html.DisplayName(" :מסמך")</h5>  
                    <div align="right">@Html.DisplayFor(model => model.namef) </div>                               
                

                @using (Html.BeginForm("DeleteFile", "CustomerClients", FormMethod.Post, new { enctype = "multipart/form-data" }))
                {
                    @Html.AntiForgeryToken()
                    <br />
                    <br /><br />
                    <div class="form-group" align="center">
                            <input type="submit" value="מחיקה" class="w3-button blue-buttonE" />&nbsp;&nbsp;&nbsp;
                            <input type="button" value="ביטול" class="w3-button blue-buttonE" onclick="location.href='@Url.Action("IndexFile")'" />
                    </div>
                }
            </div>
       
        </div>
    </div>
</div>

<script src="~/Scripts/bootstrap.min.js"></script>
<script type="text/javascript">

    $(window).on('load', function () {
        setTimeout(
            function () {
                $('#myModal').modal('show');
            }, 2000);

    });
    $('#myModal').modal({
        backdrop: 'static',
        keyboard: false
    })
</script>
@*<script src="~/Scripts/jquery-1.10.2.min.js"></script>*@

<style>
  
    .MakeWide {
        width: 250px;
    }
    .blue-buttonE {
        background-color: #6666b2 !important;
        color: white !important;
        min-width: 50px;
    }
    .modal-content {
        /*height: 1000px;*/
        /*width: 1200px;*/
        min-height: 100px;
        height: auto;
        margin: 80px auto 0px auto;
        /*padding: 10px 10px;*/
        /*overflow: auto*/
    }

    .tr11 {
        /*background-color: #CCCC00;*/
        background-color: #b8a5e4;
        color: navy;
        font-size: 18px;
    }

    td {
        /*background-color: #eff76f;*/
        background-color: #f0d7fc;
        /*color: #b8a5e4;*/
        text-align: center;
    }

    td, h3, h2, .dl-horizontal, .form-horizontal {
        color: navy;
    }

    .table {
        border-spacing: 1;
        border-collapse: collapse;
        background: white;
        border-radius: 6px;
        overflow: hidden;
        max-width: 800px;
        width: 100%;
        margin: 0 auto;
        position: relative;
    }

    .leftpane {
        width: 50%;
        float: left;
        position: fixed;
    }

    th {
        text-align: center;
    }

    a {
        color: navy
    }
</style>

Project/Views/CustomerClients/Edit.cshtml
@model Project.Models.client

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog">

            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title right">  !@ViewBag.name  שלום</h4>
                </div>
                @using (Html.BeginForm("Edit", "CustomerClients"))
                {
                    @Html.AntiForgeryToken()
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    @Html.HiddenFor(model => model.id_client)
                    @Html.HiddenFor(model => model.passwordc)
                    @Html.HiddenFor(model => model.iduser_client)
                    @Html.HiddenFor(model => model.lastorder_client)
                   <label id="salary1" hidden="hidden" >@Html.DisplayFor(model => model.salary1)</label>
                    <label id="salary2" hidden="hidden">@Html.DisplayFor(model => model.salary2)</label>
                    <label id="salary3" hidden="hidden">@Html.DisplayFor(model => model.salary3)</label>
                    <label id="salary4" hidden="hidden">@Html.DisplayFor(model => model.salary4)</label>
                    <div class="modal-body">
                        <h4 class="text-danger" style="text-align:center">@ViewBag.error1</h4>
                        <hr />
                        אנא עדכן את פרטיך האישיים להקלת הכניסה והשימוש באתר
                        <div class="form-group">
                            <div class="col-md-10">
                                <label> @Html.DisplayName(" שם ")</label>

                                @Html.EditorFor(model => model.nameclient, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.nameclient, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <label> @Html.DisplayName(" ת'ז")</label>

                                @Html.EditorFor(model => model.tz_client, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.tz_client, "", new { @class = "text-danger" })
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <label> @Html.DisplayName(" טלפון")</label>

                                @Html.EditorFor(model => model.phone_client, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.phone_client, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <h1>@ViewBag.errorp</h1>
                        <div class="form-group">
                            <div class="col-md-10">
                                <label> @Html.DisplayName(" כתובת מייל")</label>

                                @Html.EditorFor(model => model.email_client, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.email_client, "", new { @class = "text-danger" })
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>   @Html.DisplayName("עיר")</label>
                                <div style="margin-right:30%">
                                    @Html.DropDownList("idcity_client", null, htmlAttributes: new { @class = "form-control s" })
                                    @Html.ValidationMessageFor(model => model.idcity_client, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>@Html.DisplayName("שכונה")</label>
                                <div style="margin-right:30%">
                                    @Html.DropDownList("idneighborhood_client", null, htmlAttributes: new { @class = "form-control s" })
                                    @Html.ValidationMessageFor(model => model.idneighborhood_client, "", new { @class = "text-danger" })
                                </div>
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-10">
                                <label>@Html.DisplayName(" כתובת")</label>

                                @Html.EditorFor(model => model.address_client, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.address_client, "", new { @class = "text-danger" })
                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-10">
                                <label>   @Html.DisplayName("מעמד אב")</label>
                                <div style="margin-right:30%">
                                    <select id="fjob" name="fjob" class="form-control s fjob">
                                        <option value="1">לא עובד</option>
                                        <option value="2">עובד</option>
                                    </select>
                                </div>
                            </div>
                        </div>

                        <div class="form-group" id="sfather">
                            <div class="col-md-10">
                                @Html.DisplayName(" הכנס/י משכורת של חודשים האחרונים")
                                <br />

                            </div>
                            <div class="col-md-10">
                                <label> משכורת חודש</label><label id="lblmy1"></label>
                                <div style="margin-right:30%">
                                    @Html.EditorFor(model => model.salary1, new { htmlAttributes = new { @type = "number", @min = "0", @step = "0.01", @value = "0", @class = "form-control" } })
                                </div>
                            </div>
                            <div class="col-md-10">

                                <label> משכורת חודש</label><label id="lblmy2"></label>
                                <div style="margin-right:30%">
                                    @Html.EditorFor(model => model.salary2, new { htmlAttributes = new { @type = "number", @min = "0", @step = "0.01", @value = "0", @class = "form-control" } })
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-md-10">
                                <label>   @Html.DisplayName("מעמד אם")</label>
                                <div style="margin-right:30%">
                                    <select id="mjob" name="mjob" class="form-control s mjob">
                                        <option value="1" >לא עובד</option>
                                        <option value="2">עובד</option>
                                    </select>
                                </div>
                            </div>
                        </div>
                        <div class="form-group"  id="smother">
                            <div class="col-md-10">
                                @Html.DisplayName(" הכנס/י משכורת של חודשים האחרונים")
                                <br />

                            </div>
                            <div class="col-md-10">
                                <label> משכורת חודש</label><label id="lblmy3"></label>
                                <div style="margin-right:30%">
                                    @Html.EditorFor(model => model.salary3, new { htmlAttributes = new { @type = "number", @min = "0", @step = "0.01", @value = "0", @class = "form-control" } })
                                </div>
                            </div>
                            <div class="col-md-10">
                                <label> משכורת חודש</label><label id="lblmy4"></label>
                                <div style="margin-right:30%">
                                    @Html.EditorFor(model => model.salary4, new { htmlAttributes = new { @type = "number", @min = "0", @step = "0.01", @value = "0", @class = "form-control" } })
                                </div>
                            </div>

                        </div>
                        <div class="form-group">
                            <div class="col-md-10" id="nc">
                                <label> @Html.DisplayName("  מספר ילדים")</label>

                                @Html.EditorFor(model => model.numchildren_client, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.numchildren_client, "", new { @class = "text-danger" })
                                <br />
                                <br />
                            </div>
                        </div>

                        <div class="form-group" style="text-align:center">
                            <div style="align-items:center">
                                <input type="submit" value="המשך" class="w3-button blue-button" align="center" />
                            </div>
                        </div>

                    </div>
                }
            </div>
                    </div>
                </div>

<script type="text/javascript">

    $(window).on('load', function () {
        setTimeout(
            function () {
                $('#myModal').modal('show');
            }, 2100);

    });
    $('#myModal').modal({
        backdrop: 'static',
        keyboard: false
    })
    $(document).ready(function () {

        if (($('#salary1').text() != "" && $('#salary1').text() != "0") ||( $('#salary2').text() != "" && $('#salary2').text() != "0")) {
            $('#sfather').show();
            $('.fjob').val('2').prop('selected', true);
        }
        else {
            $('#smother').hide();
            $('.fjob').val('1').prop('selected', true);
        }
        if (($('#salary3').text() != "" && $('#salary3').text() != "0") ||( $('#salary4').text() != "" || $('#salary4').text() != "0")) {
            $('#smother').show();
            $('.mjob').val('2').prop('selected', true);
        }
        else {
            $('#smother').hide();
            $('.mjob').val('1').prop('selected', true);
        }
        var d = new Date();
        
        var month = d.getMonth();
        var year = d.getFullYear();
        for (i = 1; i < 4; i++)
        {
            if (month == 0)
            {
                month = 12;
                year -= 1;
            }
            $('#lblmy' + i).text(month + "/" + year);
            month--;
        }  
        $('#lblmy3').text($('#lblmy1').text());
        $('#lblmy4').text($('#lblmy2').text());
        $(".mjob").change(function () {
            if ($('#mjob').val() == "עובד" || $('#mjob').val()=="2" )
                $('#smother').show();
            else
                $('#smother').hide();
                
        });
        $(".fjob").change(function () {
            if ($('#fjob').val() == "עובד" || $('#fjob').val() == "2")
                $('#sfather').show();
            else
                $('#sfather').hide();

        });
        });
</script>
<style>
    .MakeWide {
        width: 250px;
    }

    .modal-content {
        min-height: 100px;
        height: auto;
        margin: 80px auto 0px auto;
    }
    .s {
        width: 220px;
    }

</style>

Project/Views/CustomerClients/EditDetails.cshtml
@using Project.Models
@model CustomerClientVM
@{
    ViewBag.Title = "CreateDetails";
    Layout = "~/Views/Shared/_CustomerLayout.cshtml";
}

<body>
    <div id="myModal" class="modal fade" role="dialog">
        <div class="modal-dialog" >

            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title right">  !@ViewBag.name  שלום</h4>
                </div>
                <br />
                <br />
                <h4 class="text-danger" style="text-align:right">@ViewBag.error</h4>
                @using (Html.BeginForm("Create", "Customer_children", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()
                    <div class="form-horizontal" align="center">
                        @for (int i = 0; i < Model.listChlidren.Count; i++)
                        {


                            <h1>@ViewBag.id</h1>
                            @*<hr />*@
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                            @Html.HiddenFor(model => model.listChlidren[i].id_child)
                            @Html.HiddenFor(model => model.listChlidren[i].idclient_child)
                            <div class="form-group">
                                <div class="col-md-10">
                                    <label> @Html.DisplayName(" הכנס/י תאריך לידה ")</label>
                                    @Html.EditorFor(model => model.listChlidren[i].birthdate_child, new { htmlAttributes = new { @class = "form-control MakeWide" } })
                                    @Html.ValidationMessageFor(model => model.listChlidren[i].birthdate_child, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-8">
                                    <label> @Html.DisplayName(" הכנס/י מין ")</label>
                                    @Html.DropDownListFor(model => model.listChlidren[i].m_f_child,
                                            new SelectList(Enum.GetValues(typeof(Gender))),
                                            "זכר", new { @class = "form-control MakeWide" })


                                </div>
                            </div>

                        }
                        <div class="modal-footer" style="text-align:center">
                            <input type="submit" value="המשך" class="w3-button blue-button" />
                        </div>
                    </div>

                }


            </div>

                    </div>
    </div>
</body>
<script type="text/javascript">

    $(window).on('load', function () {
        setTimeout(
            function () {
                $('#myModal').modal('show');
            }, 2000);

    });
    $('#myModal').modal({
        backdrop: 'static',
        keyboard: false
    })

</script>
<style>
    .MakeWide {
        width: 250px;
    }
    .modal-content {
        min-height: 100px;
        height: auto;
        margin: 80px auto 0px auto;     
    }
</style>