Project/Controllers/Manager_salesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Project.Models;

namespace Project.Controllers
{
    public class Manager_salesController : Controller
    {
        private P2Entities2 db = new P2Entities2();

        // GET: sales
        public ActionResult Index()
        {
            var sale = db.sale.Include(s => s.city).Include(s => s.neighborhood).Include(s => s.setting);
            return View(sale.ToList());
        }

       
        // GET: sales/Create
        public ActionResult Create()
        {
            ViewBag.idcity_sale = new SelectList(db.city, "id_city", "name_city");
            ViewBag.idneighborhood_sale = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood");
            ViewBag.numitemssetting_sale = new SelectList(db.setting, "id_setting", "id_setting");
            return View();
        }

        // POST: sales/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id_sale,name_sale,idcity_sale,idneighborhood_sale,fod_sale,lod_sale,date_sale,numitemssetting_sale,addressSale")] sale sale)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.sale.Add(sale);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.idcity_sale = new SelectList(db.city, "id_city", "name_city", sale.idcity_sale);
                ViewBag.idneighborhood_sale = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood", sale.idneighborhood_sale);
                ViewBag.numitemssetting_sale = new SelectList(db.setting, "id_setting", "id_setting", sale.numitemssetting_sale);
                return View(sale);
            }
            catch
            {
                ViewBag.error = ".ארעה שגיאה בעת שמירת הפרטים";
                return View();
            }
        }

        // GET: sales/Edit/5
        public ActionResult Edit(int? id)
        {
           try{ if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sale sale = db.sale.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            ViewBag.idcity_sale = new SelectList(db.city, "id_city", "name_city", sale.idcity_sale);
            ViewBag.idneighborhood_sale = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood", sale.idneighborhood_sale);
            ViewBag.numitemssetting_sale = new SelectList(db.setting, "id_setting", "id_setting", sale.numitemssetting_sale);
            return View(sale);
            }
            catch
            {
                ViewBag.error = ".ארעה שגיאה בעת עדכון הפרטים";
                return View();
            }
        }

        // POST: sales/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id_sale,name_sale,idcity_sale,idneighborhood_sale,fod_sale,lod_sale,date_sale,numitemssetting_sale,addressSale")] sale sale)
        {
            try{
                if (ModelState.IsValid)
            {
                db.Entry(sale).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.idcity_sale = new SelectList(db.city, "id_city", "name_city", sale.idcity_sale);
            ViewBag.idneighborhood_sale = new SelectList(db.neighborhood, "id_neighborhood", "name_neighborhood", sale.idneighborhood_sale);
            ViewBag.numitemssetting_sale = new SelectList(db.setting, "id_setting", "id_setting", sale.numitemssetting_sale);
            return View(sale);
            }
            catch
            {
                ViewBag.error = ".ארעה שגיאה בעת עדכון הפרטים";
                return View();
            }
        }

        // GET: sales/Delete/5
        public ActionResult Delete(int? id)
        {
            try{
                if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            sale sale = db.sale.Find(id);
            if (sale == null)
            {
                return HttpNotFound();
            }
            return View(sale);
            }
            catch
            {
                ViewBag.error = ".ארעה שגיאה בעת שליחת הנתונים";
                return View();
            }
        }

        // POST: sales/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try{
                sale sale = db.sale.Find(id);
                db.item_in_sale.RemoveRange(db.item_in_sale.Where(c => c.sale.id_sale == id));
                db.sale.Remove(sale);
            db.SaveChanges();
            return RedirectToAction("Index");
            }
            catch
            {
                ViewBag.error = ".ארעה שגיאה בעת מחיקת הנתונים";
                return View();
            }
        }
        [HttpPost]
        public PartialViewResult Search(string searchTxt)
        {

            var res = db.sale.Where(a => a.name_sale.Contains(searchTxt) || a.city.name_city.ToString().Contains(searchTxt) || a.neighborhood.name_neighborhood.Contains(searchTxt) ).ToList();
            if (res.Count() != 0)
            {
                return PartialView(res);
            }
            else
            {
                ViewBag.error9 = "אין תוצאות לשאילתה החיפוש שלך";
                return PartialView(res);
            }
        }
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Project/Views/Manager_sales/Create.cshtml
@model Project.Models.sale

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<h3 align="right">חדש</h3>
<div class="leftpane">
    <br /><br />
    <br />
    <img src="~/pictures/6.png" style="width:450px;height:300px" />
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" align="right">

    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.DisplayName("שם מכירה")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.name_sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name_sale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("עיר")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("idcity_sale", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idcity_sale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("שכונה")
        <br /><br />
        <div class="col-md-13">
            @Html.DropDownList("idneighborhood_sale", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idneighborhood_sale, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.DisplayName("כתובת")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.addressSale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.addressSale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("תאריך התחלה")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.fod_sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fod_sale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("תאריך סיום")
        <br /><br />
        <div class="col-md-13">
            @Html.EditorFor(model => model.lod_sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lod_sale, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
    <div class="form-group">
        <div class="col-md-offset-2" align="right">
            <input type="submit" value="שמירה" class="btn btn-my" />&nbsp;&nbsp;&nbsp;
            <input type="button" value="ביטול" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
        </div>
    </div>

}

Project/Views/Manager_sales/Delete.cshtml
@model Project.Models.sale

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}



<h3 align="right">מחיקה</h3>
<div class="leftpane">
    <br /><br />
    <br />
    <img src="~/pictures/18-806x567.png" style="width:450px;height:300px" />
</div>
<div align="right">
    <br />
    <dl class="dl-horizontal" style="margin-left:80%">
        <dt>
            @Html.DisplayFor(model => model.name_sale)
        </dt>
        <dd>
            @Html.DisplayName("מכירה")
        </dd>

        <dt>
            @Html.DisplayFor(model => model.fod_sale)
        </dt>

        <dd>
            @Html.DisplayName("תאריך התחלה")
        </dd>

        <dt>
            @Html.DisplayFor(model => model.lod_sale)
        </dt>
        <dd>
            @Html.DisplayName("תאריך סיום")
        </dd>
        <dt>
            @Html.DisplayFor(model => model.addressSale)
        </dt>

        <dd>
            @Html.DisplayName("כתובת")
        </dd>
        <dt>
            @Html.DisplayFor(model => model.city.name_city)
        </dt>

        <dd>
            @Html.DisplayName("עיר")
        </dd>
        <dt>
            @Html.DisplayFor(model => model.neighborhood.name_neighborhood)
        </dt>

        <dd>
            @Html.DisplayName("שכונה")
        </dd>
    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color" style="margin-left:50%">
            <div class="col-md-offset-2">
                <input type="submit" value="מחיקה" class="btn btn-my" />&nbsp;&nbsp;&nbsp;
                <input type="button" value="ביטול" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
            </div>
        </div>
    }
</div>

Project/Views/Manager_sales/Edit.cshtml
@model Project.Models.sale

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}


<h3 align="right">עדכון</h3>
<div class="leftpane">
    <br /><br />
    <br />

    <img src="~/pictures/9.png" style="width:450px;height:300px" />
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" align="right">

    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.id_sale)

    <div class="form-group">
        @Html.DisplayName("מכירה")
        <div class="col-md-10">
            @Html.EditorFor(model => model.name_sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.name_sale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("עיר")
        <div class="col-md-10">
            @Html.DropDownList("idcity_sale", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idcity_sale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("שכונה")
        <div class="col-md-10">
            @Html.DropDownList("idneighborhood_sale", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.idneighborhood_sale, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.DisplayName("כתובת")
        <div class="col-md-10">
            @Html.EditorFor(model => model.addressSale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.addressSale, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.DisplayName("תאריך התחלה")
        <div class="col-md-10">
            @Html.EditorFor(model => model.fod_sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.fod_sale, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.DisplayName("תאריך סיום")
        <div class="col-md-10">
            @Html.EditorFor(model => model.lod_sale, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.lod_sale, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
    <div class="form-group" style="margin-left:50%">
        <div class="col-md-offset-2 ">
            <input type="submit" value="שמירה" class="btn btn-my" />&nbsp;&nbsp;&nbsp;
            <input type="button" value="ביטול" class="btn btn-my" onclick="location.href='@Url.Action("Index")'" />
        </div>
    </div>
}

Project/Views/Manager_sales/Index.cshtml
@model IEnumerable<Project.Models.sale>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<h2 style="margin-left:8%">מכירות</h2>

<h3 style="margin-left:75%">
    @Html.ActionLink("חדש", "Create")
</h3>
<div style="margin-right:10%">
    @using (Ajax.BeginForm("Search", "Manager_sales", new AjaxOptions()
    {
        HttpMethod = "post",
        UpdateTargetId = "divSearchResults",
        InsertionMode = InsertionMode.Replace
    }))
    {
        <div align="right">
            <button type="submit" class="btn btn-default">
                <span class="glyphicon glyphicon-search"></span>
            </button>
            <input type="text" class="btn btn-default searchTxt" name="searchTxt" placeholder="חיפוש לפי מכירה/עיר/שכונה" />

        </div>
    }
    </div>
    <div id="divSearchResults">
        <br />
        <table class="table" style="text-align:left;width:80%">
            <tr class="tr11">
                <th></th>
                <th>
                    @Html.DisplayName("כתובת")
                </th>
                <th>
                    @Html.DisplayName("שכונה")
                </th>
                <th>
                    @Html.DisplayName("עיר")
                </th>
                <th>
                    @Html.DisplayName("תאריך סיום")
                </th>
                <th>
                    @Html.DisplayName("תאריך התחלה")
                </th>
                <th>
                    @Html.DisplayName("מכירה")
                </th>
            </tr>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.ActionLink("עדכון", "Edit", new { id = item.id_sale }) |
                    @Html.ActionLink("מחיקה", "Delete", new { id = item.id_sale })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.addressSale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.neighborhood.name_neighborhood)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.city.name_city)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lod_sale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fod_sale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name_sale)
                </td>
            </tr>
            }

        </table>

    </div>

Project/Views/Manager_sales/Search.cshtml
@model IEnumerable<Project.Models.sale>
@{
    Layout = "~/Views/Shared/_ManLayout.cshtml";
}

<script src="~/scripts/jquery-1.7.1.min.js"></script>
<script src="~/scripts/jquery.unobtrusive-ajax.min.js"></script>


<div id="divSearchResults" style="width:100%">
    <h2 style="margin-left:8%">מכירות</h2>

    <h3 style="margin-left:75%">
        @Html.ActionLink("חדש", "Create")
    </h3>

    <div style="margin-right:10%">
        @using (Ajax.BeginForm("Search", "Manager_sales", new AjaxOptions()
        {
            HttpMethod = "post",
            UpdateTargetId = "divSearchResults",
            InsertionMode = InsertionMode.Replace
        }))
        {
            <div align="right">
                <button type="submit" class="btn btn-default">
                    <span class="glyphicon glyphicon-search"></span>
                </button>
                <input type="text" class="btn btn-default searchTxt" name="searchTxt" placeholder="חיפוש לפי מוצר /מכירה/ עיר" />

            </div>
        }
    </div>
    <h4 class="text-danger" align="right">@ViewBag.error9</h4>
    @if (Model != null)
    {
        <br />
        <table class="table" style="text-align:left;width:80%">
            <tr class="tr11">
                <th></th>
                <th>
                    @Html.DisplayName("כתובת")
                </th>
                <th>
                    @Html.DisplayName("שכונה")
                </th>
                <th>
                    @Html.DisplayName("עיר")
                </th>
                <th>
                    @Html.DisplayName("תאריך מכירה")
                </th>
                <th>
                    @Html.DisplayName("תאריך אחרון")
                </th>
                <th>
                    @Html.DisplayName("תאריך סיום")
                </th>
                <th>
                    @Html.DisplayName("שם מכירה")
                </th>
            </tr>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.ActionLink("עדכון", "Edit", new { id = item.id_sale }) |
                    @Html.ActionLink("מחיקה", "Delete", new { id = item.id_sale })
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.addressSale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.neighborhood.name_neighborhood)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.city.name_city)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.date_sale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.lod_sale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.fod_sale)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.name_sale)
                </td>





            </tr>
            }

        </table>}
</div>